from typing import Any

Handle = tuple[int, int, int]
PortHandle = tuple[int, int, int, int]
Claim = tuple[int, str, list[int] | bytes, int, int, Handle | None]
FailureData = dict[str, Any]

class NativePublicationTicket:
    def identifier(self) -> int: ...
    def source(self) -> Handle: ...
    def status(self) -> str: ...
    def report(self) -> dict[str, Any] | None: ...

class NativeCounter:
    @property
    def owner(self) -> Handle: ...
    @property
    def source(self) -> Handle: ...
    @property
    def counter(self) -> Handle: ...
    @property
    def sink(self) -> Handle: ...
    def stats(self) -> dict[str, int | None]: ...

class NativeComponent:
    @property
    def owner(self) -> Handle: ...
    def stats(self) -> dict[str, int]: ...

class NativeWorld:
    def __init__(self, *, max_actors: int = 128, mailbox_capacity: int = 64,
                 mailbox_bytes: int = 65536, native_payload_budget: int = 4194304,
                 max_subscriptions: int = 512, max_event_bytes: int = 32768,
                 max_tasks: int = 256, max_operations: int = 256,
                 diagnostic_capacity: int = 1024, max_schemas: int = 128,
                 max_services: int = 64, max_service_leases: int = 1024,
                 max_leases_per_actor: int = 16,
                 max_publications: int = 256,
                 max_publications_per_source: int = 32,
                 max_publication_fanout: int = 4096,
                 max_routing_snapshot_entries: int = 16384,
                 routing_batch_size: int = 32,
                 virtual_time: bool = False, cpu_workers: int = 2,
                 max_cpu_jobs: int = 32) -> None: ...
    def cpu_stats(self) -> dict[str, int]: ...
    def cpu_sum_squares(self, parent: Handle | None = None) -> Handle: ...
    def register_service(self, name: str, target: Handle, descriptor: tuple) -> None: ...
    def acquire_service(self, owner: Handle, name: str, descriptor: tuple,
                        expected_service: Handle | None = None) -> tuple[Handle, Handle]: ...
    def service_request(self, scope: Handle, owner: Handle, service: Handle, port: str,
                        kind: str, values: list[int] | bytes, schema: int,
                        deadline_ms: int, options: Any = None,
                        claim_token: int | None = None) -> Handle: ...
    def service_link(self, scope: Handle, owner: Handle, service: Handle,
                     output: str, target: PortHandle) -> int: ...
    def release_service(self, scope: Handle, owner: Handle, service: Handle) -> bool: ...
    def register_schemas(self, descriptors: tuple) -> list[int]: ...
    def register_component(self, owner: Handle, descriptor: tuple) -> list[PortHandle]: ...
    def component(self, owner: Handle) -> dict[str, Any] | None: ...
    def require_interface(self, owner: Handle, descriptor: tuple) -> None: ...
    def port(self, owner: Handle, name: str) -> PortHandle: ...
    def link(self, owner: Handle, source: PortHandle, target: PortHandle) -> int: ...
    def send_port(self, target: PortHandle, kind: str, values: list[int] | bytes, schema: int) -> int: ...
    def publish_port(self, source: PortHandle, kind: str, values: list[int] | bytes, schema: int, claim_token: int | None = None, options: Any = None) -> NativePublicationTicket: ...
    def prepare_component(self, parent: Handle, kind: str, period_ms: int = 0) -> NativeComponent: ...
    def allocate(self, python: bool = True, parent: Handle | None = None) -> Handle: ...
    def activate(self, reference: Handle) -> None: ...
    def state(self, reference: Handle) -> str: ...
    def ready_cutoff(self) -> int: ...
    def ready_next(self, phase: str, after: int | None = None,
                   through: int = 0) -> tuple[int, Handle] | None: ...
    def send(self, reference: Handle, kind: str, values: list[int] | bytes, schema: int = 0, options: Any = None, claim_token: int | None = None) -> int: ...
    def subscribe(self, source: Handle, target: Handle) -> int: ...
    def unsubscribe(self, token: int) -> None: ...
    def claim(self, reference: Handle) -> Claim | None: ...
    def finish(self, token: int, success: bool = True) -> None: ...
    def stop(self, reference: Handle) -> dict[str, Any]: ...
    def stop_report(self, reference: Handle | None = None) -> dict[str, Any]: ...
    def cancel_all(self) -> dict[str, Any]: ...
    def drain(self, reference: Handle, deadline_ms: int) -> dict[str, Any]: ...
    def drain_all(self, deadline_ms: int) -> dict[str, Any]: ...
    def finish_python(self, reference: Handle) -> None: ...
    def snapshot(self) -> dict[str, Any]: ...
    def wait(self, milliseconds: int) -> None: ...
    def counter(self, parent: Handle | None, interval_ms: int, window_ms: int,
                python_target: Handle | None = None) -> NativeCounter: ...
    def after(self, owner: Handle, target: Handle, delay_ms: int, kind: str,
              values: list[int] | bytes, schema: int = 0, options: Any = None, claim_token: int | None = None) -> None: ...
    def request(self, owner: Handle, target: Handle, kind: str, values: list[int] | bytes,
                schema: int = 0, timeout_ms: int = 1000, options: Any = None, claim_token: int | None = None) -> Handle: ...
    def reply(self, id: Handle, target: Handle, kind: str,
              values: list[int] | bytes, schema: int = 0, options: Any = None) -> bool: ...
    def claim_metadata(self, token: int) -> dict[str, Any]: ...
    def operation_status(self, id: Handle) -> dict[str, Any]: ...
    def take_operation(self, id: Handle) -> dict[str, Any] | None: ...
    def cancel_operation(self, id: Handle) -> bool: ...
    def diagnostics(self, after_sequence: int = 0, limit: int = 100) -> dict[str, Any]: ...
    def report_failure(self, reference: Handle, phase: str, handler: str,
                       exception_type: str, frames: list[tuple[str, int, str]],
                       action: str, event_id: int | None = None,
                       schema: int | None = None,
                       operation: Handle | None = None,
                       truncated: bool = False) -> FailureData: ...
    def claim_failure(self, supervisor: Handle) -> tuple[int, FailureData, int] | None: ...
    def finish_failure(self, token: int, action: str | None = None) -> None: ...
    def close(self, timeout_ms: int = 1000) -> dict[str, Any]: ...
