from typing import Any
from .authoring import ActorRef, OperationHandle, World

class TestStepLimit(RuntimeError): ...

class PendingNative:
    operation: tuple[int, int, int]
    def __init__(self, operation: tuple[int, int, int]) -> None: ...

class TestWorld(World):
    __test__: bool
    def __init__(self, *, max_steps: int = ..., **kwargs: Any) -> None: ...
    def now(self) -> float: ...
    def step(self) -> int: ...
    def run_until_idle(self, max_steps: int | None = ...) -> int: ...
    def advance(self, seconds: float, *, max_steps: int | None = ..., dispatch_python: bool = ...) -> int: ...
    def run_for(self, duration: float) -> None: ...
    def run(self, duration: float | None = ...) -> None: ...
    def native_responder(self, event_type: type, parent: ActorRef | None = ...) -> ActorRef: ...
    def pending_native(self) -> tuple[PendingNative, ...]: ...
    def complete(self, operation: OperationHandle, event: Any) -> bool: ...
    def close(self, timeout: float = ..., *, mode: str | None = ...) -> dict: ...
